/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dashboard/anuncios': RouteRecordInfo<'/dashboard/anuncios', '/dashboard/anuncios', Record<never, never>, Record<never, never>>,
    '/dashboard/ayuda': RouteRecordInfo<'/dashboard/ayuda', '/dashboard/ayuda', Record<never, never>, Record<never, never>>,
    '/dashboard/calendario': RouteRecordInfo<'/dashboard/calendario', '/dashboard/calendario', Record<never, never>, Record<never, never>>,
    '/dashboard/calificaciones': RouteRecordInfo<'/dashboard/calificaciones', '/dashboard/calificaciones', Record<never, never>, Record<never, never>>,
    '/dashboard/dashboard': RouteRecordInfo<'/dashboard/dashboard', '/dashboard/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/matricula': RouteRecordInfo<'/dashboard/matricula', '/dashboard/matricula', Record<never, never>, Record<never, never>>,
    '/dashboard/registro': RouteRecordInfo<'/dashboard/registro', '/dashboard/registro', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/dashboard/anuncios.vue': {
      routes: '/dashboard/anuncios'
      views: never
    }
    'src/pages/dashboard/ayuda.vue': {
      routes: '/dashboard/ayuda'
      views: never
    }
    'src/pages/dashboard/calendario.vue': {
      routes: '/dashboard/calendario'
      views: never
    }
    'src/pages/dashboard/calificaciones.vue': {
      routes: '/dashboard/calificaciones'
      views: never
    }
    'src/pages/dashboard/dashboard.vue': {
      routes: '/dashboard/dashboard'
      views: never
    }
    'src/pages/dashboard/matricula.vue': {
      routes: '/dashboard/matricula'
      views: never
    }
    'src/pages/dashboard/registro.vue': {
      routes: '/dashboard/registro'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
